#theme: jekyll-theme-architect
#title: Rajdeep Baruri
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-cayman
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-dinky
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-hacker
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!


#theme: jekyll-theme-leap-day
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-merlot
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!


#theme: jekyll-theme-midnight
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-minimal
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!


#theme: jekyll-theme-minimal
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-modernist
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!


#theme: jekyll-theme-slate
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-tactile
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!

#theme: jekyll-theme-time-machine
#title: Octocat's homepage
#description: Bookmark this to keep an eye on my project updates!


